### ISSUE TITLE
Latest version of Docker cli need libglapi

### ISSUE THREAD

**Issue by ryanneufeld** [cturra/docker-dropbox#11]
Docker will segfault if it's missing the library from a fresh install.

A quick google suggested a fix.
https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Headless-install-on-Debian-libglapi-so-0-cannot-open-shared/td-p/396457

```
dropbox: setting args
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/apex._apex.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/dropbox/.dropbox-dist/dropbox-lnx.x86_64-96.4.172/PyQt5.QtWidgets.cpython-37m-x86_64-linux-gnu.so'
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 265, in <module>
  File "dropbox/foundation/navigation_service/factory.pyc", line 22, in <module>
  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 58, in <module>
  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 12, in <module>
  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>
  File "dropbox/client/features/model_registry.pyc", line 13, in <module>
  File "dropbox/client/features/generated_models.pyc", line 283, in <module>
  File "dropbox/client/features/previews/view_anchor.pyc", line 107, in <module>
  File "<_bootstrap_overrides>", line 153, in load_module
ImportError: libglapi.so.0: cannot open shared object file: No such file or directory
!! dropbox: fatal python exception:
['Traceback (most recent call last):\n', '  File "dropbox/client/main.pyc", line 265, in <module>\n', '  File "dropbox/foundation/navigation_service/factory.pyc", line 22, in <module>\n', '  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 58, in <module>\n', '  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 12, in <module>\n', '  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>\n', '  File "dropbox/client/features/model_registry.pyc", line 13, in <module>\n', '  File "dropbox/client/features/generated_models.pyc", line 283, in <module>\n', '  File "dropbox/client/features/previews/view_anchor.pyc", line 107, in <module>\n', '  File "<_bootstrap_overrides>", line 153, in load_module\n', 'ImportError: libglapi.so.0: cannot open shared object file: No such file or directory\n'] (error 3)
```

**Comment by cturra** [comment]
following up on pr #13, this issue should now be resolved. thanks again for your help @ryanneufeld 🎉
